--[[
    @Author: Yuerer
    @Date: 2021-05-27 14:12:20
    To run some OP_CODE jit tests, run the following command:
    path.lua all.lua
]] 

dofile("0_OP_MOVE.lua")
dofile("1_OP_LOADK.lua")
dofile("3_OP_LOADBOOL.lua")
dofile("4_OP_LOADNIL.lua")
dofile("5_OP_GETUPVAL.lua")
dofile("6_OP_GETTABUP.lua")
dofile("7_OP_GETTABLE.lua")
dofile("8_OP_SETTABUP.lua")
dofile("9_OP_SETUPVAL.lua")
dofile("10_OP_SETTABLE.lua")
dofile("11_OP_NEWTABLE.lua")
dofile("12_OP_SELF.lua")
dofile("13_OP_ADD.lua")
dofile("14_OP_SUB.lua")
dofile("15_OP_MUL.lua")
dofile("16_OP_MOD.lua")
dofile("17_OP_POW.lua")
dofile("18_OP_DIV.lua")
dofile("19_OP_IDIV.lua")
dofile("20_OP_BAND.lua")
dofile("21_OP_BOR.lua")
dofile("22_OP_BXOR.lua")
dofile("23_OP_SHL.lua")
dofile("24_OP_SHR.lua")
dofile("25_OP_UNM.lua")
dofile("26_OP_BNOT.lua")
dofile("27_OP_NOT.lua")
dofile("28_OP_LEN.lua")
dofile("29_OP_CONCAT.lua")
dofile("30_OP_JMP.lua")
dofile("31_OP_EQ.lua")
dofile("34_OP_TEST.lua")
dofile("35_OP_TESTSET.lua")
dofile("36_OP_CALL.lua")
dofile("38_OP_RETURN.lua")
dofile("40_OP_FORPREP.lua")
dofile("42_OP_TFORLOOP.lua")
dofile("43_OP_SETLIST.lua")
dofile("44_OP_CLOSURE.lua")
dofile("45_OP_VARARG.lua")

print("all OP_CODE jit tests ok")